import json
import unittest

from tooling import load

gen = load('tools/gen_rules.py')


def rules(**fields):
    base = {'firstDifference': -1,
            'baseExp': [[0] * 20, [100] * 20, [120] * 10 + [130] * 10],
            'difficulty': [{'minExp': 120, 'con': 'Tough'}, {'minExp': 100, 'con': 'EvenMatch'}],
            'incrediblyEasyPrey': {'minLevel': 255, 'minExp': 255},
            'sittingAnimations': [33, 47, 63]}
    base.update(fields)
    return base


class Parse(unittest.TestCase):
    def test_the_written_format_reads_back(self):
        self.assertEqual(gen.parse(gen.format_rules(rules())), rules())

    def assertBad(self, message, **fields):
        with self.assertRaises(gen.DataError) as caught:
            gen.parse(json.dumps(rules(**fields)), 'x.json')
        self.assertIn('x.json', str(caught.exception))
        self.assertIn(message, str(caught.exception))

    def test_a_row_of_the_wrong_width(self):
        self.assertBad('baseExp row 1 must have 20 columns', baseExp=[[0] * 20, [0] * 19])

    def test_experience_out_of_range(self):
        self.assertBad('baseExp row 0 must be a whole number from 0 to 65535', baseExp=[[-1] + [0] * 19])
        self.assertBad('baseExp row 0 must be a whole number from 0 to 65535', baseExp=[[True] + [0] * 19])

    def test_an_unknown_con(self):
        self.assertBad('difficulty step 0 must be a minExp and one of', difficulty=[{'minExp': 1, 'con': 'Easy'}])

    def test_empty_tables(self):
        self.assertBad('baseExp has no rows', baseExp=[])
        self.assertBad('difficulty has no steps', difficulty=[])
        self.assertBad('sittingAnimations is empty', sittingAnimations=[])

    def test_sitting_animations_must_be_a_set_in_order(self):
        self.assertBad('strictly increasing', sittingAnimations=[47, 33])
        self.assertBad('strictly increasing', sittingAnimations=[33, 33])
        self.assertBad('a sitting animation must be a whole number from 0 to 255', sittingAnimations=[256])

    def test_missing_or_extra_keys(self):
        broken = rules()
        del broken['incrediblyEasyPrey']
        with self.assertRaises(gen.DataError) as caught:
            gen.parse(json.dumps(broken), 'x.json')
        self.assertIn('x.json: expected the keys firstDifference baseExp', str(caught.exception))
        self.assertBad('expected the keys firstDifference baseExp', extra=1)
        self.assertBad('incrediblyEasyPrey must have minLevel and minExp', incrediblyEasyPrey={'minLevel': 1})

    def test_not_json(self):
        with self.assertRaises(gen.DataError) as caught:
            gen.parse('{', 'x.json')
        self.assertIn('x.json: not JSON', str(caught.exception))


class Format(unittest.TestCase):
    def test_a_row_per_line(self):
        lines = gen.format_rules(rules()).splitlines()
        self.assertIn('    [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, '
                      '100],', lines)
        self.assertIn('    {"minExp": 120, "con": "Tough"},', lines)
        self.assertIn('  "sittingAnimations": [33, 47, 63]', lines)


class Generate(unittest.TestCase):
    def setUp(self):
        self.text = gen.generate(rules(), 'abc123')

    def test_names_the_commit(self):
        self.assertTrue(self.text.startswith(
            '// Generated by tools/gen_rules.py from data/phoenix_rules.json (Phoenix abc123). Do not edit.'))

    def test_the_table_keeps_its_rows_and_first_difference(self):
        self.assertIn('    constexpr int kFirstDifference = -1;', self.text)
        self.assertIn('    constexpr uint16_t kBaseExp[3][20] = {', self.text)
        self.assertIn('        {120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 130, 130, 130, 130, 130, 130, 130, 130, '
                      '130, 130},', self.text)

    def test_the_curve_keeps_phoenixs_order(self):
        self.assertIn('        {120, Con::Tough},\n        {100, Con::EvenMatch},', self.text)

    def test_incredibly_easy_prey_and_sitting(self):
        self.assertIn('    constexpr int kIncrediblyEasyPreyMinLevel    = 255;', self.text)
        self.assertIn('    constexpr uint32_t kIncrediblyEasyPreyMinExp = 255;', self.text)
        self.assertIn('    constexpr uint32_t kSittingAnimations[] = {33, 47, 63};', self.text)


if __name__ == '__main__':
    unittest.main()
