import pathlib
import tempfile
import unittest

from tooling import load

gen = load('tools/gen_mobdata.py')

HEADER = 'id\tzone\tname\tminLevel\tmaxLevel\tflags\trespawn\tdetects\texpLevelMod\tplaceholderOf'
GOOD = (HEADER + '\n17190918\t101\tWild Rabbit\t1\t1\t0\t60\t257\t-2\t0\n'
        '17191194\t101\tCarrion Worm\t4\t5\t0\t180\t2\t0\t17191196\n'
        '17199648\t103\tGoblin Bounty Hunter\t17\t20\t161\t300\t259\t0\t0\n')


class Parse(unittest.TestCase):
    def test_rows(self):
        records = gen.parse(GOOD)
        self.assertEqual(len(records), 3)
        self.assertEqual(records[2], {'id': 17199648, 'zone': 103, 'name': 'Goblin Bounty Hunter', 'minLevel': 17,
                                      'maxLevel': 20, 'flags': 161, 'respawn': 300, 'detects': 259, 'expLevelMod': 0,
                                      'placeholderOf': 0})
        self.assertEqual(records[1]['placeholderOf'], 17191196)

    def test_a_level_mod_can_be_negative(self):
        self.assertEqual(gen.parse(GOOD)[0]['expLevelMod'], -2)

    def assertBadRow(self, row, message):
        with self.assertRaises(gen.DataError) as caught:
            gen.parse(HEADER + '\n' + row + '\n', 'x.tsv')
        self.assertIn('x.tsv:2:', str(caught.exception))
        self.assertIn(message, str(caught.exception))

    def test_bad_rows_name_their_line(self):
        self.assertBadRow('1\t103\tA\t1\t2\t0\t0\t0\t0', 'expected 10 columns')
        self.assertBadRow('1\t103\t\t1\t2\t0\t0\t0\t0\t0', 'empty name')
        self.assertBadRow('1\t103\tA\t1\t300\t0\t0\t0\t0\t0', 'maxLevel must be')
        self.assertBadRow('1\t103\tA\t-1\t2\t0\t0\t0\t0\t0', 'minLevel must be')
        self.assertBadRow('1\t103\tA\t5\t2\t0\t0\t0\t0\t0', 'minLevel is above maxLevel')
        self.assertBadRow('1\t103\tA\t1\t2\t256\t0\t0\t0\t0', 'flags must be')
        self.assertBadRow('1\t103\tA\t1\t2\t0\t0\t65536\t0\t0', 'detects must be')
        self.assertBadRow('1\t103\tA\t1\t2\t0\t0\t0\t-32769\t0', 'expLevelMod must be')
        self.assertBadRow('1\t103\tA\t1\t2\t0\t0\t0\t--2\t0', 'expLevelMod must be')
        self.assertBadRow('1\t103\tA\t1\t2\t0\t0\t0\t0\t-1', 'placeholderOf must be')

    def test_ids_must_increase(self):
        with self.assertRaises(gen.DataError) as caught:
            gen.parse(HEADER + '\n5\t1\tA\t1\t1\t0\t0\t0\t0\t0\n5\t1\tB\t1\t1\t0\t0\t0\t0\t0\n')
        self.assertIn(':3: ids must be strictly increasing', str(caught.exception))

    def test_wrong_header(self):
        with self.assertRaises(gen.DataError):
            gen.parse('id\tname\n1\tA\n')


class Output(unittest.TestCase):
    def test_c_strings_escape_quotes_backslashes_and_non_ascii(self):
        self.assertEqual(gen.c_string("Do'Bho"), '"Do\'Bho"')
        self.assertEqual(gen.c_string('a"b\\c?'), '"a\\042b\\134c?"')
        self.assertEqual(gen.c_string('é'), '"\\303\\251"')

    def test_record_line(self):
        records = gen.parse(GOOD)
        self.assertEqual(gen.c_record(records[2]), '    {17199648u, "Goblin Bounty Hunter", 17, 20, 161, 300u, 259, 0, 0u},')
        self.assertEqual(gen.c_record(records[0]), '    {17190918u, "Wild Rabbit", 1, 1, 0, 60u, 257, -2, 0u},')
        self.assertEqual(gen.c_record(records[1]), '    {17191194u, "Carrion Worm", 4, 5, 0, 180u, 2, 0, 17191196u},')

    def test_generate_names_the_commit(self):
        text = gen.generate(gen.parse(GOOD), 'abc123')
        self.assertTrue(text.startswith('// Generated by tools/gen_mobdata.py from data/phoenix_mobs.tsv (Phoenix abc123)'))
        self.assertIn('const MobRecord kMobs[] = {', text)

    def test_the_plugin_gets_every_bit_under_its_cpp_name(self):
        text = gen.generate_flags()
        self.assertIn('enum MobFlag : uint8_t', text)
        self.assertIn('        kMobAlwaysAggro = 2,', text)
        self.assertIn('        kMobTrueDetection = 64,', text)
        self.assertIn('        kMobFollows = 128,', text)
        self.assertIn('enum MobDetect : uint16_t', text)
        self.assertIn('        kDetectLowHp = 4,', text)

    def test_a_meta_file_without_the_commit_is_an_error(self):
        with tempfile.TemporaryDirectory() as tmp:
            meta = pathlib.Path(tmp) / 'phoenix_mobs.meta'
            meta.write_text('mobs\t3\n')
            with self.assertRaises(gen.DataError) as caught:
                gen.read_commit(meta)
            self.assertIn('no phoenix_commit line', str(caught.exception))
            meta.write_text('generated\tnow\nphoenix_commit\tabc123\n')
            self.assertEqual(gen.read_commit(meta), 'abc123')


if __name__ == '__main__':
    unittest.main()
