import importlib.util
import pathlib
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location('gen_mobdata', ROOT / 'tools' / 'gen_mobdata.py')
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)

HEADER = 'id\tzone\tname\tminLevel\tmaxLevel\tflags\trespawn\tdetects'
GOOD = (HEADER + '\n17199577\t103\tGoblins Dragonfly\t28\t30\t0\t0\t1\n'
        '17199648\t103\tGoblin Bounty Hunter\t17\t20\t65\t300\t259\n')


class Parse(unittest.TestCase):
    def test_rows(self):
        records = gen.parse(GOOD)
        self.assertEqual(len(records), 2)
        self.assertEqual(records[1], {'id': 17199648, 'zone': 103, 'name': 'Goblin Bounty Hunter', 'minLevel': 17,
                                      'maxLevel': 20, 'flags': 65, 'respawn': 300, 'detects': 259})

    def assertBadRow(self, row, message):
        with self.assertRaises(gen.DataError) as caught:
            gen.parse(HEADER + '\n' + row + '\n', 'x.tsv')
        self.assertIn('x.tsv:2:', str(caught.exception))
        self.assertIn(message, str(caught.exception))

    def test_bad_rows_name_their_line(self):
        self.assertBadRow('1\t103\tA\t1\t2\t0\t0', 'expected 8 columns')
        self.assertBadRow('1\t103\t\t1\t2\t0\t0\t0', 'empty name')
        self.assertBadRow('1\t103\tA\t1\t300\t0\t0\t0', 'maxLevel must be')
        self.assertBadRow('1\t103\tA\t-1\t2\t0\t0\t0', 'minLevel must be')
        self.assertBadRow('1\t103\tA\t5\t2\t0\t0\t0', 'minLevel is above maxLevel')
        self.assertBadRow('1\t103\tA\t1\t2\t256\t0\t0', 'flags must be')
        self.assertBadRow('1\t103\tA\t1\t2\t0\t0\t65536', 'detects must be')

    def test_ids_must_increase(self):
        with self.assertRaises(gen.DataError) as caught:
            gen.parse(HEADER + '\n5\t1\tA\t1\t1\t0\t0\t0\n5\t1\tB\t1\t1\t0\t0\t0\n')
        self.assertIn(':3: ids must be strictly increasing', str(caught.exception))

    def test_wrong_header(self):
        with self.assertRaises(gen.DataError):
            gen.parse('id\tname\n1\tA\n')


class Output(unittest.TestCase):
    def test_c_strings_escape_quotes_backslashes_and_non_ascii(self):
        self.assertEqual(gen.c_string("Do'Bho"), '"Do\'Bho"')
        self.assertEqual(gen.c_string('a"b\\c?'), '"a\\042b\\134c?"')
        self.assertEqual(gen.c_string('é'), '"\\303\\251"')

    def test_record_line(self):
        record = gen.parse(GOOD)[1]
        self.assertEqual(gen.c_record(record), '    {17199648u, 103, "Goblin Bounty Hunter", 17, 20, 65, 300u, 259},')

    def test_generate_names_the_commit(self):
        text = gen.generate(gen.parse(GOOD), 'abc123')
        self.assertTrue(text.startswith('// Generated by tools/gen_mobdata.py from data/phoenix_mobs.tsv (Phoenix abc123)'))
        self.assertIn('const MobRecord kMobs[] = {', text)


if __name__ == '__main__':
    unittest.main()
