#!/usr/bin/env python3
"""Generate src/generated/icons.inc from the MobDB icons in third_party/mobdb-icons (MIT License, ThornyFFXI).

The PNG files are compiled into the plugin as byte arrays; Ashita decodes them when an icon primitive is created.
"""
import pathlib
import sys

# src/icons.cpp builds its table from these arrays in aggroglow::Icon order.
ICONS = ['AggroNQ', 'AggroHQ', 'PassiveNQ', 'PassiveHQ', 'Link', 'Sight', 'TrueSight', 'Sound', 'Scent', 'Magic', 'JA',
         'Blood']
PNG_SIGNATURE = b'\x89PNG\r\n\x1a\n'
# src/icons.cpp reads the width and height from the IHDR chunk that must follow the signature.
IHDR_TYPE = slice(12, 16)
MAX_BYTES = 64 * 1024


class IconError(ValueError):
    pass


def c_array(name: str, data: bytes) -> str:
    lines = [f'const unsigned char kPng{name}[] = {{']
    for start in range(0, len(data), 16):
        lines.append('    ' + ' '.join(f'0x{b:02x},' for b in data[start:start + 16]))
    lines.append('};')
    return '\n'.join(lines)


def generate(icon_dir: pathlib.Path) -> str:
    parts = ['// Generated by tools/gen_icons.py from third_party/mobdb-icons (MIT License, ThornyFFXI). Do not edit.']
    for name in ICONS:
        path = pathlib.Path(icon_dir) / f'{name}.png'
        if not path.is_file():
            raise IconError(f'missing icon {path}')
        data = path.read_bytes()
        if not data.startswith(PNG_SIGNATURE) or data[IHDR_TYPE] != b'IHDR' or len(data) > MAX_BYTES:
            raise IconError(f'{path} is not a PNG of at most {MAX_BYTES} bytes')
        parts.append(c_array(name, data))
    return '\n'.join(parts) + '\n'


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    out = root / 'src' / 'generated' / 'icons.inc'
    try:
        text = generate(root / 'third_party' / 'mobdb-icons')
    except IconError as error:
        print(f'gen_icons: {error}', file=sys.stderr)
        return 1
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.exists() or out.read_text(encoding='utf-8') != text:
        out.write_text(text, encoding='utf-8')
    print(f'icons: {len(ICONS)} -> {out}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
