#!/usr/bin/env python3
"""Generate src/generated/mobdb_data.inc from the vendored MobDB zone files (third_party/mobdb/data/<zone>.lua)."""
import pathlib
import re
import sys

RECORD = re.compile(
    r"Name='((?:[^'\\]|\\.)*)', Notorious=(true|false), Aggro=(true|false), .*?MinLevel=(\d+), MaxLevel=(\d+)")
INDEX_KEY = re.compile(r"^\s*\[(\d+)\] = \{")


def unescape(lua: str) -> str:
    return re.sub(r"\\(.)", r"\1", lua)


def parse_zone(text: str, zone: int):
    """Returns (spawn records keyed by entity index, records keyed by name) for one zone file."""
    by_index, by_name, section = [], [], None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith('Names = {'):
            section = 'names'
            continue
        if stripped.startswith('Indices = {'):
            section = 'indices'
            continue
        m = RECORD.search(line)
        if section is None or not m:
            continue
        rec = {'zone': zone, 'index': 0, 'name': unescape(m.group(1)), 'notorious': m.group(2) == 'true',
               'aggro': m.group(3) == 'true', 'min': int(m.group(4)), 'max': int(m.group(5))}
        if section == 'indices':
            key = INDEX_KEY.match(line)
            if not key:
                continue
            rec['index'] = int(key.group(1))
            by_index.append(rec)
        else:
            by_name.append(rec)
    return by_index, by_name


def c_string(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def c_record(r) -> str:
    return (f"    {{{r['zone']}, {r['index']}, {c_string(r['name'])}, {str(r['aggro']).lower()}, "
            f"{str(r['notorious']).lower()}, {r['min']}, {r['max']}}},")


def generate(data_dir: pathlib.Path) -> str:
    by_index, by_name = [], []
    for path in data_dir.glob('*.lua'):
        idx, names = parse_zone(path.read_text(encoding='utf-8', errors='replace'), int(path.stem))
        by_index += idx
        by_name += names
    by_index.sort(key=lambda r: (r['zone'], r['index']))
    by_name.sort(key=lambda r: (r['zone'], r['name'].encode('utf-8')))  # byte order, matching std::string_view
    lines = ['// Generated by tools/gen_mobdb.py from third_party/mobdb (MIT License, ThornyFFXI). Do not edit.',
             f'// {len(by_index)} spawn records, {len(by_name)} name records.',
             'const MobRecord kByIndex[] = {']
    lines += [c_record(r) for r in by_index]
    lines += ['};', '', 'const MobRecord kByName[] = {']
    lines += [c_record(r) for r in by_name]
    lines += ['};', '']
    return '\n'.join(lines)


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    out = root / 'src' / 'generated' / 'mobdb_data.inc'
    out.parent.mkdir(parents=True, exist_ok=True)
    text = generate(root / 'third_party' / 'mobdb' / 'data')
    if not out.exists() or out.read_text(encoding='utf-8') != text:
        out.write_text(text, encoding='utf-8')
    print(f'mobdb: {out}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
