#!/usr/bin/env python3
"""Generate src/generated/fonts.inc from the fonts in third_party/fonts.

Each font is embedded byte for byte; src/fonts.cpp hands the bytes to Windows, which loads them for this process only.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from gen_icons import c_bytes  # noqa: E402

# The fonts in the order the font dropdown offers them: the family GDI matches on, the symbol, and the file.
FONTS = [
    ('Marcellus SC', 'kFontMarcellusSC', 'MarcellusSC-Regular.ttf'),
    ('Cinzel', 'kFontCinzel', 'Cinzel-Regular.ttf'),
    ('Cormorant SC', 'kFontCormorantSC', 'CormorantSC-SemiBold.ttf'),
]


class FontError(ValueError):
    pass


def generate(fonts: pathlib.Path) -> str:
    parts = ['// Generated by tools/gen_fonts.py from third_party/fonts. Do not edit.']
    for _, symbol, filename in FONTS:
        path = fonts / filename
        if not path.is_file():
            raise FontError(f'missing font {path}')
        parts.append(c_bytes(symbol, path.read_bytes()))
    rows = ', '.join(f'{{"{family}", {symbol}, sizeof({symbol})}}' for family, symbol, _ in FONTS)
    parts.append(f'const BundledFont kBundledFonts[] = {{{rows}}};')
    return '\n'.join(parts) + '\n'


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    out = root / 'src' / 'generated' / 'fonts.inc'
    try:
        text = generate(root / 'third_party' / 'fonts')
    except FontError as error:
        print(f'gen_fonts: {error}', file=sys.stderr)
        return 1
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding='utf-8')
    print(f'fonts: {len(FONTS)} bundled -> {out}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
