#!/usr/bin/env python3
"""Generate src/generated/pointer.inc from the chocobo mouse pointer in third_party/playonline-chocobo.

The animated cursor file is embedded byte for byte; src/cursor_file.cpp reads its frames.
"""
import pathlib
import sys

BYTES_PER_LINE = 16


class PointerError(ValueError):
    pass


def generate(path: pathlib.Path) -> str:
    if not path.is_file():
        raise PointerError(f'missing pointer {path}')
    data = path.read_bytes()
    lines = ['// Generated by tools/gen_pointer.py from third_party/playonline-chocobo. Do not edit.',
             'const unsigned char kChocoboPointerFile[] = {']
    for start in range(0, len(data), BYTES_PER_LINE):
        lines.append('    ' + ' '.join(f'0x{b:02x},' for b in data[start:start + BYTES_PER_LINE]))
    lines.append('};')
    return '\n'.join(lines) + '\n'


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    try:
        text = generate(root / 'third_party' / 'playonline-chocobo' / 'chocobo.ani')
    except PointerError as error:
        print(f'gen_pointer: {error}', file=sys.stderr)
        return 1
    out = root / 'src' / 'generated' / 'pointer.inc'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding='utf-8')
    return 0


if __name__ == '__main__':
    sys.exit(main())
