#!/usr/bin/env python3
"""Generate src/generated/mobdata.inc and mobflags.h from data/phoenix_mobs.tsv (written by tools/phoenix/refresh.sh).

This file owns the TSV's format: its columns and ranges, the bits of its flags and detects columns, the names of the
data files and the meta file's commit key. The Phoenix tools import it, and the plugin gets the bits from mobflags.h.
"""
import enum
import pathlib
import re
import sys

TSV_NAME = 'phoenix_mobs.tsv'
META_NAME = 'phoenix_mobs.meta'
META_COMMIT_KEY = 'phoenix_commit'
COLUMNS = ['id', 'zone', 'name', 'minLevel', 'maxLevel', 'flags', 'respawn', 'detects', 'expLevelMod', 'placeholderOf']
LIMITS = {'id': (1, 0xFFFFFFFF), 'zone': (0, 0xFFFF), 'minLevel': (0, 255), 'maxLevel': (0, 255), 'flags': (0, 0xFF),
          'respawn': (0, 0xFFFFFFFF), 'detects': (0, 0xFFFF), 'expLevelMod': (-0x8000, 0x7FFF),
          'placeholderOf': (0, 0xFFFFFFFF)}


class MobFlag(enum.IntFlag):
    AGGRESSIVE = 1       # m_Aggro
    ALWAYS_AGGRO = 2     # MobMod AlwaysAggro: aggros even when Too Weak
    NO_AGGRO = 4         # MobMod NoAggro
    NOTORIOUS = 8        # MobType Notorious
    LINK = 32            # m_Link: links with its family
    TRUE_DETECTION = 64  # m_TrueDetection: true sight or true sound
    FOLLOWS = 128        # RoamFlag Follow: follows players instead of aggroing


class Detect(enum.IntFlag):
    """Phoenix's MobMod Detection (data/enums/detects.yaml)."""
    SIGHT = 0x001
    HEARING = 0x002
    LOW_HP = 0x004
    MAGIC = 0x020
    ABILITY = 0x040  # job abilities and weapon skills
    SCENT = 0x100


class DataError(ValueError):
    pass


def parse(text: str, source: str = TSV_NAME):
    lines = text.splitlines()
    if not lines or lines[0].split('\t') != COLUMNS:
        raise DataError(f'{source}:1: expected the header ' + ' '.join(COLUMNS))
    records, last_id = [], 0
    for number, line in enumerate(lines[1:], start=2):
        fields = line.split('\t')
        if len(fields) != len(COLUMNS):
            raise DataError(f'{source}:{number}: expected {len(COLUMNS)} columns, got {len(fields)}')
        record = {}
        for column, value in zip(COLUMNS, fields):
            if column == 'name':
                if not value:
                    raise DataError(f'{source}:{number}: empty name')
                record[column] = value
                continue
            lo, hi = LIMITS[column]
            if not re.fullmatch(r'-?[0-9]+', value) or not lo <= int(value) <= hi:
                raise DataError(f'{source}:{number}: {column} must be a whole number from {lo} to {hi}, got {value!r}')
            record[column] = int(value)
        if record['minLevel'] > record['maxLevel']:
            raise DataError(f'{source}:{number}: minLevel is above maxLevel')
        if record['id'] <= last_id:
            raise DataError(f'{source}:{number}: ids must be strictly increasing')
        last_id = record['id']
        records.append(record)
    return records


def c_string(text: str) -> str:
    out = []
    for byte in text.encode('utf-8'):
        char = chr(byte)
        out.append(char if 0x20 <= byte < 0x7F and char not in '"\\' else f'\\{byte:03o}')
    return '"' + ''.join(out) + '"'


def c_record(r) -> str:
    return (f"    {{{r['id']}u, {c_string(r['name'])}, {r['minLevel']}, {r['maxLevel']}, {r['flags']}, {r['respawn']}u, "
            f"{r['detects']}, {r['expLevelMod']}, {r['placeholderOf']}u}},")


def generate(records, commit: str) -> str:
    lines = [f'// Generated by tools/gen_mobdata.py from data/{TSV_NAME} (Phoenix {commit}). Do not edit.',
             f'// {len(records)} mobs, sorted by server ID.',
             'const MobRecord kMobs[] = {']
    lines += [c_record(r) for r in records]
    lines += ['};', '']
    return '\n'.join(lines)


def cpp_enum(name: str, prefix: str, underlying: str, flags) -> list:
    def words(member):
        return ''.join(part.capitalize() for part in member.name.split('_'))
    return [f'    enum {name} : {underlying}', '    {'] + [f'        {prefix}{words(m)} = {m.value},' for m in flags] + ['    };']


def generate_flags() -> str:
    lines = ['// Generated by tools/gen_mobdata.py. Do not edit.', '#pragma once', '', '#include <cstdint>', '',
             'namespace headsup', '{', '    // Bits of MobRecord::flags.']
    lines += cpp_enum('MobFlag', 'kMob', 'uint8_t', MobFlag)
    lines += ['', "    // Bits of MobRecord::detects: Phoenix's MobMod Detection."]
    lines += cpp_enum('MobDetect', 'kDetect', 'uint16_t', Detect)
    lines += ['}', '']
    return '\n'.join(lines)


def read_commit(meta: pathlib.Path) -> str:
    for line in meta.read_text(encoding='utf-8').splitlines():
        key, _, value = line.partition('\t')
        if key == META_COMMIT_KEY:
            return value
    raise DataError(f'{meta}: no {META_COMMIT_KEY} line')


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    generated = root / 'src' / 'generated'
    try:
        records = parse((root / 'data' / TSV_NAME).read_text(encoding='utf-8'), str(root / 'data' / TSV_NAME))
        text = generate(records, read_commit(root / 'data' / META_NAME))
    except DataError as error:
        print(f'gen_mobdata: {error}', file=sys.stderr)
        return 1
    generated.mkdir(parents=True, exist_ok=True)
    (generated / 'mobdata.inc').write_text(text, encoding='utf-8')
    (generated / 'mobflags.h').write_text(generate_flags(), encoding='utf-8')
    print(f'mobdata: {len(records)} mobs -> {generated}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
