#!/usr/bin/env python3
"""Generate src/generated/shapes.inc from the Phoenix feather icon in third_party/phoenix-feather.

The SVG's one path is flattened into straight segments and scaled into a unit box; HeadsUp fills that polygon at
whatever size it draws the target cursor.
"""
import pathlib
import re
import sys

SEGMENTS = 12  # straight pieces per cubic curve
PATH = re.compile(r'<path\b[^>]*\bd="([^"]*)"')
TOKEN = re.compile(r'[A-Za-z]|-?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?')
ARGUMENTS = {'M': 2, 'L': 2, 'C': 6, 'Z': 0}


class ShapeError(ValueError):
    pass


def cubic(p0, p1, p2, p3, t):
    u = 1.0 - t
    return tuple(u * u * u * a + 3 * u * u * t * b + 3 * u * t * t * c + t * t * t * d for a, b, c, d in zip(p0, p1, p2, p3))


def polygon(d: str, segments: int = SEGMENTS) -> tuple[list[tuple[float, float]], float]:
    """The path's points scaled into the unit box (x right, y down), and its height over its width. Only one closed
    outline of absolute M, L and C commands is read."""
    tokens = TOKEN.findall(d)
    points, command, i = [], None, 0
    while i < len(tokens):
        if tokens[i].isalpha():
            command = tokens[i]
            i += 1
            if command not in ARGUMENTS:
                raise ShapeError(f'unsupported path command {command}')
            if command == 'Z':
                if i != len(tokens):
                    raise ShapeError('only one closed outline is supported')
                break
            if command == 'M' and points:
                raise ShapeError('only one closed outline is supported')
        elif command is None:
            raise ShapeError('the path does not start with a command')
        count = ARGUMENTS[command]
        arguments = tokens[i:i + count]
        if len(arguments) != count or any(v.isalpha() for v in arguments):
            raise ShapeError(f'{command} needs {count} numbers')
        values = [float(v) for v in arguments]
        i += count
        if command == 'C':
            start, c1, c2, end = points[-1], tuple(values[0:2]), tuple(values[2:4]), tuple(values[4:6])
            points += [cubic(start, c1, c2, end, step / segments) for step in range(1, segments + 1)]
        else:
            points.append(tuple(values))
            if command == 'M':
                command = 'L'  # further pairs after a move are lines
    if len(points) < 3:
        raise ShapeError('the path has no outline')
    if points[-1] == points[0]:
        points.pop()
    xs, ys = [p[0] for p in points], [p[1] for p in points]
    left, top, width, height = min(xs), min(ys), max(xs) - min(xs), max(ys) - min(ys)
    if width <= 0 or height <= 0:
        raise ShapeError('the outline has no area')
    return [((x - left) / width, (y - top) / height) for x, y in points], height / width


def generate(svg: pathlib.Path, segments: int = SEGMENTS) -> str:
    match = PATH.search(pathlib.Path(svg).read_text(encoding='utf-8'))
    if match is None:
        raise ShapeError(f'{svg} has no path')
    points, aspect = polygon(match.group(1), segments)
    lines = ['// Generated by tools/gen_shapes.py from third_party/phoenix-feather/logo_icon.svg. Do not edit.',
             f'constexpr float kFeatherAspect = {aspect:.4f}f;', 'const ShapePoint kFeatherPoints[] = {']
    lines += [f'    {{{x:.4f}f, {y:.4f}f}},' for x, y in points]
    lines.append('};')
    return '\n'.join(lines) + '\n'


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    out = root / 'src' / 'generated' / 'shapes.inc'
    try:
        text = generate(root / 'third_party' / 'phoenix-feather' / 'logo_icon.svg')
    except ShapeError as error:
        print(f'gen_shapes: {error}', file=sys.stderr)
        return 1
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.exists() or out.read_text(encoding='utf-8') != text:
        out.write_text(text, encoding='utf-8')
    print(f'shapes: feather -> {out}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
