#!/usr/bin/env python3
"""Generate src/generated/phoenix_rules.h from data/phoenix_rules.json (written by tools/phoenix/refresh.sh).

This file owns the JSON's format. Every value is what Phoenix's map server loaded: the base experience table that
charutils::GetBaseExp reads, the difficulty curve and Incredibly Easy Prey rule of charutils::CheckMob, and the
animations CBattleEntity::isSitting counts as sitting.
"""
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import gen_mobdata  # noqa: E402

RULES_NAME = 'phoenix_rules.json'
KEYS = ['firstDifference', 'baseExp', 'difficulty', 'incrediblyEasyPrey', 'sittingAnimations']
# Phoenix's EMobDifficulty in order; the plugin's Con has the same names.
CONS = ['TooWeak', 'IncrediblyEasyPrey', 'EasyPrey', 'DecentChallenge', 'EvenMatch', 'Tough', 'VeryTough',
        'IncrediblyTough']
COLUMNS = 20  # GetBaseExp's player level brackets, 1-5 to 96-100
MAX_EXP = 0xFFFF
MAX_LEVEL = 0xFFFF
MAX_ANIMATION = 0xFF

DataError = gen_mobdata.DataError


def whole(value, lo, hi, what):
    if type(value) is not int or not lo <= value <= hi:
        raise DataError(f'{what} must be a whole number from {lo} to {hi}, got {value!r}')
    return value


def parse(text: str, source: str = RULES_NAME):
    try:
        rules = json.loads(text)
    except json.JSONDecodeError as error:
        raise DataError(f'{source}: not JSON ({error})') from error
    if not isinstance(rules, dict) or sorted(rules) != sorted(KEYS):
        raise DataError(f'{source}: expected the keys ' + ' '.join(KEYS))
    whole(rules['firstDifference'], -MAX_EXP, MAX_EXP, f'{source}: firstDifference')
    rows = rules['baseExp']
    if not isinstance(rows, list) or not rows:
        raise DataError(f'{source}: baseExp has no rows')
    for n, row in enumerate(rows):
        if not isinstance(row, list) or len(row) != COLUMNS:
            raise DataError(f'{source}: baseExp row {n} must have {COLUMNS} columns')
        for value in row:
            whole(value, 0, MAX_EXP, f'{source}: baseExp row {n}')
    steps = rules['difficulty']
    if not isinstance(steps, list) or not steps:
        raise DataError(f'{source}: difficulty has no steps')
    for n, step in enumerate(steps):
        if not isinstance(step, dict) or sorted(step) != ['con', 'minExp'] or step['con'] not in CONS:
            raise DataError(f'{source}: difficulty step {n} must be a minExp and one of ' + ' '.join(CONS))
        whole(step['minExp'], 0, MAX_EXP, f'{source}: difficulty step {n} minExp')
    prey = rules['incrediblyEasyPrey']
    if not isinstance(prey, dict) or sorted(prey) != ['minExp', 'minLevel']:
        raise DataError(f'{source}: incrediblyEasyPrey must have minLevel and minExp')
    whole(prey['minLevel'], 0, MAX_LEVEL, f'{source}: incrediblyEasyPrey minLevel')
    whole(prey['minExp'], 0, MAX_EXP, f'{source}: incrediblyEasyPrey minExp')
    animations = rules['sittingAnimations']
    if not isinstance(animations, list) or not animations:
        raise DataError(f'{source}: sittingAnimations is empty')
    for animation in animations:
        whole(animation, 0, MAX_ANIMATION, f'{source}: a sitting animation')
    if animations != sorted(set(animations)):
        raise DataError(f'{source}: sittingAnimations must be strictly increasing')
    return rules


def format_rules(rules) -> str:
    """The JSON with a row per line, so a refresh's diff shows which values moved."""
    def rows(items):
        return ',\n'.join('    ' + json.dumps(item) for item in items)
    return (f'{{\n  "firstDifference": {rules["firstDifference"]},\n'
            f'  "baseExp": [\n{rows(rules["baseExp"])}\n  ],\n'
            f'  "difficulty": [\n{rows(rules["difficulty"])}\n  ],\n'
            f'  "incrediblyEasyPrey": {json.dumps(rules["incrediblyEasyPrey"])},\n'
            f'  "sittingAnimations": {json.dumps(rules["sittingAnimations"])}\n}}\n')


def generate(rules, commit: str) -> str:
    prey = rules['incrediblyEasyPrey']
    lines = [f'// Generated by tools/gen_rules.py from data/{RULES_NAME} (Phoenix {commit}). Do not edit.',
             '#pragma once', '', '#include "con.h"', '', '#include <cstdint>', '', 'namespace headsup', '{',
             '    // Base experience by level difference (mob - player) from kFirstDifference, a column per five player '
             'levels.',
             f'    constexpr int kFirstDifference = {rules["firstDifference"]};',
             f'    constexpr uint16_t kBaseExp[{len(rules["baseExp"])}][{COLUMNS}] = {{']
    lines += ['        {' + ', '.join(str(v) for v in row) + '},' for row in rules['baseExp']]
    lines += ['    };', '',
              '    // /check: the first step whose experience the mob gives reaches minExp, hardest first.',
              '    struct DifficultyStep', '    {', '        uint32_t minExp;', '        Con con;', '    };',
              '    constexpr DifficultyStep kDifficulty[] = {']
    lines += [f'        {{{step["minExp"]}, Con::{step["con"]}}},' for step in rules['difficulty']]
    lines += ['    };', '',
              '    // Below the curve: Incredibly Easy Prey from a mob of at least this level giving at least this '
              'experience.',
              f'    constexpr int kIncrediblyEasyPreyMinLevel    = {prey["minLevel"]};',
              f'    constexpr uint32_t kIncrediblyEasyPreyMinExp = {prey["minExp"]};', '',
              '    // The animations that let a Too Weak aggressive mob aggro.',
              '    constexpr uint32_t kSittingAnimations[] = {' + ', '.join(str(a) for a in rules['sittingAnimations'])
              + '};', '}', '']
    return '\n'.join(lines)


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    path = root / 'data' / RULES_NAME
    try:
        rules = parse(path.read_text(encoding='utf-8'), str(path))
        text = generate(rules, gen_mobdata.read_commit(root / 'data' / gen_mobdata.META_NAME))
    except DataError as error:
        print(f'gen_rules: {error}', file=sys.stderr)
        return 1
    generated = root / 'src' / 'generated'
    generated.mkdir(parents=True, exist_ok=True)
    (generated / 'phoenix_rules.h').write_text(text, encoding='utf-8')
    print(f'rules: {len(rules["baseExp"])} experience rows, {len(rules["difficulty"])} difficulty steps -> {generated}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
