#!/usr/bin/env python3
"""Generate src/generated/mobdata.inc from data/phoenix_mobs.tsv (written by tools/phoenix/refresh.sh)."""
import pathlib
import sys

COLUMNS = ['id', 'zone', 'name', 'minLevel', 'maxLevel', 'flags', 'respawn', 'detects']
LIMITS = {'id': (1, 0xFFFFFFFF), 'zone': (0, 0xFFFF), 'minLevel': (0, 255), 'maxLevel': (0, 255), 'flags': (0, 255),
          'respawn': (0, 0xFFFFFFFF), 'detects': (0, 0xFFFF)}


class DataError(ValueError):
    pass


def parse(text: str, source: str = 'phoenix_mobs.tsv'):
    lines = text.splitlines()
    if not lines or lines[0].split('\t') != COLUMNS:
        raise DataError(f'{source}:1: expected the header ' + ' '.join(COLUMNS))
    records, last_id = [], 0
    for number, line in enumerate(lines[1:], start=2):
        fields = line.split('\t')
        if len(fields) != len(COLUMNS):
            raise DataError(f'{source}:{number}: expected {len(COLUMNS)} columns, got {len(fields)}')
        record = {}
        for column, value in zip(COLUMNS, fields):
            if column == 'name':
                if not value:
                    raise DataError(f'{source}:{number}: empty name')
                record[column] = value
                continue
            lo, hi = LIMITS[column]
            if not value.isdigit() or not lo <= int(value) <= hi:
                raise DataError(f'{source}:{number}: {column} must be a whole number from {lo} to {hi}, got {value!r}')
            record[column] = int(value)
        if record['minLevel'] > record['maxLevel']:
            raise DataError(f'{source}:{number}: minLevel is above maxLevel')
        if record['id'] <= last_id:
            raise DataError(f'{source}:{number}: ids must be strictly increasing')
        last_id = record['id']
        records.append(record)
    return records


def c_string(text: str) -> str:
    out = []
    for byte in text.encode('utf-8'):
        char = chr(byte)
        out.append(char if 0x20 <= byte < 0x7F and char not in '"\\' else f'\\{byte:03o}')
    return '"' + ''.join(out) + '"'


def c_record(r) -> str:
    return (f"    {{{r['id']}u, {r['zone']}, {c_string(r['name'])}, {r['minLevel']}, {r['maxLevel']}, {r['flags']}, "
            f"{r['respawn']}u, {r['detects']}}},")


def generate(records, commit: str) -> str:
    lines = [f'// Generated by tools/gen_mobdata.py from data/phoenix_mobs.tsv (Phoenix {commit}). Do not edit.',
             f'// {len(records)} mobs, sorted by server ID.',
             'const MobRecord kMobs[] = {']
    lines += [c_record(r) for r in records]
    lines += ['};', '']
    return '\n'.join(lines)


def read_commit(meta: pathlib.Path) -> str:
    for line in meta.read_text(encoding='utf-8').splitlines():
        key, _, value = line.partition('\t')
        if key == 'phoenix_commit':
            return value
    return 'unknown commit'


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    tsv = root / 'data' / 'phoenix_mobs.tsv'
    out = root / 'src' / 'generated' / 'mobdata.inc'
    try:
        records = parse(tsv.read_text(encoding='utf-8'), str(tsv))
    except DataError as error:
        print(f'gen_mobdata: {error}', file=sys.stderr)
        return 1
    text = generate(records, read_commit(root / 'data' / 'phoenix_mobs.meta'))
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.exists() or out.read_text(encoding='utf-8') != text:
        out.write_text(text, encoding='utf-8')
    print(f'mobdata: {len(records)} mobs -> {out}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
